<?php

/**
 * @file
 * OpenEuropa Editorial Corporate Workflow Translation module file.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function oe_editorial_corporate_workflow_translation_node_presave(EntityInterface $entity) {
  // Whenever we save a translation, we need to ensure that we maintain its
  // status the same as the source. This is the default behaviour for "synced"
  // translations. Later, we will introduce the "un-synced" translations by
  // which we will keep the translations unpublished even if the source language
  // is published.
  if (!$entity->isDefaultTranslation()) {
    // If we are saving a translation entity directly, look at the source
    // translation for the correct status.
    $source = $entity->getUntranslated();
    if ($source->get('status')->value !== $entity->get('status')->value) {
      $entity->set('status', $source->get('status'));
    }

    return;
  }

  // Otherwise, loop through all the translations and set the status based on
  // the source.
  $languages = $entity->getTranslationLanguages(FALSE);
  foreach ($languages as $language) {
    $translation = $entity->getTranslation($language->getId());
    if ($translation->get('status')->value !== $entity->get('status')->value) {
      $translation->set('status', $entity->get('status')->value);
    }
  }

  // @todo, when introducing the "un-synced" translations, we need to apply
  // a check to determine whether the entity status stays synced.
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for the Node entity.
 */
function oe_editorial_corporate_workflow_translation_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // If we are rendering a translation, we should hide the content moderation
  // block because the workflow needs to be controlled from the source entity.
  if ($entity->isDefaultTranslation()) {
    return;
  }

  if (isset($build['content_moderation_control'])) {
    $build['content_moderation_control']['#access'] = FALSE;
  }
}
