<?php

/**
 * @file
 * OpenEuropa Editorial Content Lock module.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 */
function oe_editorial_content_lock_install() {
  // Set default settings for Content Lock.
  $locked_contents = [
    'file' => [
      '*' => '*',
    ],
    'node' => [
      '*' => '*',
    ],
  ];
  \Drupal::configFactory()
    ->getEditable('content_lock.settings')
    ->set('types', $locked_contents)
    ->save();
}
