<?php

/**
 * @file
 * OpenEuropa Editorial Corporate Workflow install.
 */

use Drupal\user\Entity\Role;

declare(strict_types = 1);

/**
 * Add missing permission for Validator.
 */
function oe_editorial_corporate_workflow_update_8001(array &$sandbox): void {
  $role = Role::load('oe_validator');
  $role
    ->grantPermission('use oe_corporate_workflow transition validated_to_draft')
    ->save();
}
