<?php

/**
 * @file
 * OpenEuropa Editorial Corporate Workflow module.
 */

declare(strict_types=1);

use Drupal\Core\Batch\BatchBuilder;
use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\oe_editorial_corporate_workflow\EntityStateTransitionBatch;
use Drupal\workflows\Entity\Workflow;

/**
 * Implements hook_menu_local_tasks_alter().
 */
function oe_editorial_corporate_workflow_menu_local_tasks_alter(&$data): void {
  /** @var \Drupal\workflows\WorkflowInterface $workflow */
  $workflow = Workflow::load('oe_corporate_workflow');
  $entity_types = $workflow->get('type_settings')['entity_types'];
  $entity = NULL;
  foreach (array_keys($entity_types) as $entity_type) {
    $route_entity = \Drupal::routeMatch()->getParameter($entity_type);
    if (!$route_entity instanceof ContentEntityInterface) {
      continue;
    }

    if (!in_array($route_entity->bundle(), $entity_types[$entity_type])) {
      continue;
    }

    $entity = $route_entity;
    break;
  }

  if (!$entity) {
    return;
  }

  $entity_type = $entity->getEntityTypeId();

  // Edit tab.
  if (!empty($data['tabs'][0]['entity.' . $entity_type . '.edit_form']['#link'])) {
    if (_oe_editorial_corporate_workflow_is_last_revision_published($entity)) {
      $data['tabs'][0]['entity.' . $entity_type . '.edit_form']['#link']['title'] = t('New draft');
    }
    else {
      $data['tabs'][0]['entity.' . $entity_type . '.edit_form']['#link']['title'] = t('Edit draft');
    }
  }

  // Latest revision tab.
  if (!empty($data['tabs'][0]['content_moderation.workflows:' . $entity_type . '.latest_version_tab'])) {
    $data['tabs'][0]['content_moderation.workflows:' . $entity_type . '.latest_version_tab']['#link']['title'] = t('View draft');
    $data['tabs'][0]['content_moderation.workflows:' . $entity_type . '.latest_version_tab']['#weight'] = -1;
  }

  // View tab.
  if (!empty($data['tabs'][0]['entity.' . $entity_type . '.canonical']['#link'])) {
    /** @var \Drupal\content_moderation\ModerationInformationInterface $moderation_info */
    $moderation_info = \Drupal::service('content_moderation.moderation_information');
    if ($moderation_info->isDefaultRevisionPublished($entity) || $moderation_info->isLiveRevision($entity)) {
      $data['tabs'][0]['entity.' . $entity_type . '.canonical']['#link']['title'] = t('View published');
    }
    else {
      $data['tabs'][0]['entity.' . $entity_type . '.canonical']['#link']['title'] = t('View draft');
    }
    $data['tabs'][0]['entity.' . $entity_type . '.canonical']['#weight'] = 0;
  }
}

/**
 * Implements hook_form_alter().
 *
 * Force the Draft state on corporate workflow forms.
 */
function oe_editorial_corporate_workflow_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  if (!$form_object instanceof ContentEntityForm) {
    return;
  }

  $entity = $form_object->getEntity();
  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderation_info */
  $moderation_info = \Drupal::service('content_moderation.moderation_information');
  /** @var \Drupal\workflows\WorkflowInterface $workflow */
  $workflow = $moderation_info->getWorkflowForEntity($entity);
  if (!$workflow || $workflow->id() !== 'oe_corporate_workflow') {
    return;
  }

  $form_options = &$form['moderation_state']['widget'][0]['state']['#options'];
  if (empty($form_options)) {
    return;
  }

  // Enforce Draft state in forms if we are on the original language. We don't
  // need to do this in case we are on the translation.
  if ($entity->isDefaultTranslation()) {
    $options = [
      'draft' => $workflow->getTypePlugin()->getState('draft')->label(),
    ];
    $form_options = $options;
  }

  // Remove access because either Draft is the only option or the moderation
  // state cannot be changed.
  $form['moderation_state']['#access'] = FALSE;
  if ($entity->isDefaultTranslation()) {
    $form['moderation_state']['widget'][0]['state']['#default_value'] = 'draft';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For the content moderation block form to make sure next state is selected
 * in the widget.
 */
function oe_editorial_corporate_workflow_form_content_moderation_entity_moderation_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (empty($form['new_state']['#options'])) {
    return;
  }

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $form_state->get('entity');
  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderation_info */
  $moderation_info = \Drupal::service('content_moderation.moderation_information');
  /** @var \Drupal\workflows\WorkflowInterface $workflow */
  $workflow = $moderation_info->getWorkflowForEntity($entity);

  if (!$workflow || $workflow->id() !== 'oe_corporate_workflow') {
    return;
  }

  if (count($form['new_state']['#options']) > 1) {
    $upcoming_transitions = $workflow->getTypePlugin()->getTransitionsForState($entity->moderation_state->value);
    $transition = end($upcoming_transitions);
    if (in_array($transition->to()->id(), array_keys($form['new_state']['#options']))) {
      $form['new_state']['#default_value'] = $transition->to()->id();
    }
  }

  // Define our submit callback as the first to execute.
  array_unshift($form['#submit'], '_oe_editorial_corporate_workflow_moderation_submit');
}

/**
 * Callback to handle revisions when shortcuts are used on the moderation form.
 *
 * We need to make sure that intermediary states and revisions are saved so that
 * related events are executed at every step.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function _oe_editorial_corporate_workflow_moderation_submit(array &$form, FormStateInterface &$form_state): void {
  /** @var \Drupal\oe_editorial_corporate_workflow\Services\ShortcutRevisionHandler $shortcut_handler */
  $shortcut_handler = \Drupal::service('oe_editorial_corporate_workflow.shortcut_transition_handler');

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $form_state->get('entity');
  $transitions = $shortcut_handler->getTransitionsToState($entity, $form_state->getValue('new_state'));

  // If only one transition is needed, it will be taken care by the default
  // submit handler of the form.
  if (count($transitions) === 1) {
    return;
  }

  // Extract the target states of each transition.
  $states = [];
  foreach ($transitions as $transition) {
    $states[] = $transition->to()->id();
  }

  $batch_instance = \Drupal::service('class_resolver')->getInstanceFromDefinition(EntityStateTransitionBatch::class);
  $batch = (new BatchBuilder())
    ->setInitMessage(t('Preparing to execute moderation state transitions.'))
    ->setProgressMessage(t('Executing moderation state transitions.'))
    ->addOperation([$batch_instance, 'execute'], [
      $entity,
      $states,
      $form_state->getValue('revision_log'),
    ])
    ->setFinishCallback([$batch_instance, 'finish']);
  batch_set($batch->toArray());
}

/**
 * Helper function to determine if the last revision is published.
 *
 * @param \Drupal\Core\Entity\ContentEntityInterface $entity
 *   The entity.
 *
 * @return bool
 *   True if the entity is published.
 */
function _oe_editorial_corporate_workflow_is_last_revision_published(ContentEntityInterface $entity): bool {
  // We bail out if the entity is new (has no ID).
  if ($entity->isNew()) {
    return FALSE;
  }

  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderation_info */
  $moderation_info = \Drupal::service('content_moderation.moderation_information');
  $storage = \Drupal::entityTypeManager()->getStorage($entity->getEntityTypeId());
  $latest_revision_id = $storage->getLatestTranslationAffectedRevisionId($entity->id(), $entity->language()->getId());

  return $latest_revision_id !== NULL && !$moderation_info->hasPendingRevision($entity) && $moderation_info->isDefaultRevisionPublished($entity);
}
